config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :tickets
    resources :microposts do
      resources :favorites
    end
  end

  resources :questions do
    resources :answers
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  match 'users/:id' => 'users#show', via: :get
  resources :users, only: [:show]
  root "pages#index"
  get "pages/show"
  get "pages/help"
  get "pages/contact"
  get "pages/about"

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
	mount_uploader :event_image, EventImageUploader
	has_many :tickets, dependent: :destroy
	has_many :microposts, dependent: :destroy
	belongs_to :user, class_name: 'User'
	validates :name, length: { maximum: 50 }, presence: true
	validates :content, length: { maximum: 2000 }, presence: true

	def created_by?(user)
		return false unless user
		user_id == user.id
	end

	def self.ransackable_attributes(auth_object = nil)
		%w(name)
	end

	def self.ransackable_associations(auth_object = nil)
		[]
	end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :favorites
  mount_uploader :micropost_image, MicropostImageUploader

end

app/models/question.rb
class Question < ActiveRecord::Base
		belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
   	mount_uploader :user_image, UserImageUploader
    validates :name, presence: true, length: { maximum: 20}
    has_many :created_events, class_name: 'Event', foreign_key: :user_id
    has_many :tickets
    has_many :microposts
    has_many :favorites

    def self.from_omniauth(auth)
        where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.username = auth["info"]["nickname"]
        end
    end

    def self.new_with_session(params, session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"], without_protection: true) do |user|
                user.attributes = params
                user.valid?
            end
        else
            super
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	PER = 10
	before_filter :authenticate_user!

	def index
		if params[:category_id].nil?
			@search = Event.page(params[:page]).per(PER).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		else
			@search = Event.page(params[:page]).per(PER).where(category_id: params[:category_id]).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		end
	end

	def edit
		@event = current_user.created_events.find(params[:id])
	end

	def update
		@event = current_user.created_events.find(params[:id])
		if @event.update(event_params)
			redirect_to @event, notice: '更新しました'
		else
			render :edit
		end
	end

	def destroy
		@event = current_user.created_events.find(params[:id])
		@event.destroy!
		redirect_to root_path, notice: '削除しました'
	end

	def new
		@event = current_user.created_events.build
	end

	def create
		@event = current_user.created_events.build(event_params)
		if @event.save
			redirect_to @event, notice: 'いどばたを作成しました'
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
		@ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
		@tickets = @event.tickets.includes(:user).order(:created_at)
		@microposts = @event.microposts.includes(:user).order(:created_at)
	end

	private
	def event_params
		params[:event][:address_status] = current_user.address_status
		params.require(:event).permit(
			:name, :content, :category_id, :address_status,
			:event_image, :event_image_cache, :remove_event_image
		)
	end

	private
	def search_params
		params.require(:q).permit!
	rescue
		{ name_qteq: "" }
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_filter :authenticate_user!

	def now
		raise ActionController::RoutingError 'ログイン状態で TicketsController#new にアクセス'
	end

	def create
		favorite = current_user.favorites.build do |t|
			t.micropost_id = params[:micropost_id]
		end
		if favorite.save
			redirect_to event_microposts_path(favorite.micropost.event)
		else
			render json: { messages: ticket.errors.full_messages }, status: 422
		end
	end

	def destroy
		favorite = current_user.favorites.find_by(micropost_id: params[:micropost_id])
		favorite.destroy!
		redirect_to event_microposts_path(favorite.micropost.event)
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    count = 0
    if user_signed_in?
      current_user.microposts.each do |m|
        count = count + m.favorites.count
      end
    end
    @count = count
  end

  def show
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :authenticate_user!

	def now
		raise ActionController::RoutingError 'ログイン状態で TicketsController#new にアクセス'
	end

	def create
		ticket = current_user.tickets.build do |t|
			t.event_id = params[:event_id]
			t.comment = params[:ticket][:comment]
		end
		if ticket.save
			flash[:notice] = 'このイベントに参加表明しました'
			head 201
		else
			render json: { messages: ticket.errors.full_messages }, status: 422
		end
	end

	def destroy
		ticket = current_user.tickets.find_by(event_id: params[:event_id])
		ticket.destroy!
		redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    	base_title = "Sil-地域子育て情報コミュニティ"
    	if page_title.empty?
      		base_title
    	else
      		"#{base_title} | #{page_title}"
    	end
  	end

  	def nl2br(str)
		str.gsub(/\r\n|\r|\n/, "<br />").html_safe
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pc/users/show.html.erb
<div class="row-fluid">
    <div class="span12">
      <h1>プロフィール</h1>
      <h2><%= @user.name %></h2>
      <div class="thumnail">
        <%= image_tag @user.user_image.url,:size => "100x100" %>
      </div>
      <h3><%= @user.name %></h3>
      <h3>投稿数:<%= @user.microposts.count %></h3>
      <h3>お役立ち数:<%= @user.microposts.count %></h3>
  </div>
</div>

app/views/smartphone/events/edit.html.erb
<% now = Time.zone.now %>

<div class="page-header">
	<h1>いどばた情報編集</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
	<% if @event.errors.any? %>
		<div class="alert alert-danger">
			<ul>
			<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<% if @event.event_image? %>
		<div class="thumbnail">
			<%= image_tag @event.event_image.url %>
		</div>
		<div class="">
		<% end %>
		<%= f.file_field :event_image %>
		<%= f.hidden_field :event_image_cache %>
	</div>
	<% if @event.event_image? %>
		<div class="checkbox">
			<label>
				<%= f.check_box :remove_event_image %>
				画像を削除する
			</label>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, class: 'form-control', row: 10 %>
	</div>

	<%= f.submit 'いどばた更新', class: "btn btn-large btn-warning", data: { disable_with: 'いどばた更新中…' } %>
<% end %>

app/views/smartphone/events/index.html.erb
<div class="page-header">
	<% if params[:category_id] == "1" then %>
		<h1>地域イベント・遊び場一覧</h1>
	<% elsif params[:category_id] == "2" then %>
		<h1>病院関連</h1>
	<% elsif params[:category_id] == "3" then %>
		<h1>防犯情報</h1>
	<% elsif params[:category_id] == "4" then %>
		<h1>子育て相談</h1>
	<% elsif params[:category_id] == "5" then %>
		<h1>おさがりフリマ</h1>
	<% elsif params[:category_id] == "6" then %>
		<h1>サークル</h1>
	<% elsif params[:category_id] == "7" then %>
		<h1>サイト利用者交流</h1>
	<% else %>
		<h1>いどばた一覧</h1>
	<% end %>
 </div>
 <div class="list-group">
 	<% @events.each do |event| %>
 		<%= link_to(event, class: 'list-group-item') do %>
 		<h4 class="list-group-item-heading">
 		<%= event.name %>
 		</h4>
 		<p class="list-group-item-text">
 			<%= event.created_at.strftime('%Y/%m/%d %H:%M') %>
 		</p>
 		<% end %>
 	<% end %>
 	<%= paginate @events %>
 </div>

app/views/smartphone/events/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
	<h1>いどばた作成</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
	<% if @event.errors.any? %>
		<div class="alert alert-danger">
			<ul>
			<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :category_id %>
		<% if current_user.id == 3 %>
		<%= f.select :category_id, [["地域イベント・遊び場", 1], ["病院関連", 2], ["子育て相談", 4], ["おさがりフリマ", 5], ["サイト利用者交流", 7]], class: 'form-control' %>
		<% elsif %>
		<%= f.select :category_id, [["地域イベント・遊び場", 1], ["病院関連", 2], ["防犯情報", 3], ["子育て相談", 4], ["おさがりフリマ", 5]], class: 'form-control' %>
		<% end %>
	</div>
	<div class="form-group">
		<% if @event.event_image? %>
		<div class="thumbnail">
			<%= image_tag @event.event_image.url %>
		</div>
		<% end %>
		<%= f.file_field :event_image %>
		<%= f.hidden_field :event_image_cache %>
	</div>
	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, class: 'form-control', row: 10 %>
	</div>

	<%= f.submit 'いどばた作成', class: "btn btn-large btn-warning", data: { disable_with: 'いどばた作成中…' } %>
<% end %>

app/views/smartphone/events/show.html.erb
<div class="page-header">
	<h1>
		<%= @event.name %>
	</h1>
</div>

<div>
	<div>
		<% if @event.event_image? %>
			<div class="thumnail">
				<%= image_tag @event.event_image.url %>
			</div>
		<% end %>
	</div>
<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">主催者</div>
	</div>
	<div class="panel-body">
		<% if @event.user %>
		<%= @event.user.name %>
		<% else %>
		退会したユーザーです
		<% end %>
	</div>
</div>

<div class="panel panel-primary">
	<div class="panel-heading">
		イベント内容
	</div>
	<div class="panel-body">
		<%= auto_link(nl2br(@event.content), html: { target: '_blank' }, link: :urls) %>
	</div>
</div>
	<% if @event.category_id == 1 %>
	<hr>
		<div class="panel panel-default">
			<div class="panel-heading">
				参加者
			</div>
			<div class="panel-body">
				<ul class="list-unstyled">
					<% @tickets.each do |ticket| %>
						<% if ticket.user %>
						<li>
							<%= ticket.user.name %>
							<%= ticket.comment %>
						</li>
						<% else %>
						退会したユーザーです
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
	<% end %>
	<hr>
	<div>
		<%= link_to 'いどばたに参加', event_microposts_path(@event), class: "btn btn-primary" %>
	</div>
	<hr>
	<div>
	<% if @event.created_by?(current_user) %>
		<%= link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info' %>
		<%= link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger', method: :delete, data: { confirm: '本当に削除いたしますか？'} %>
	<% end %>
	<% if @event.category_id == 1 %>
	<% if @ticket %>
		<%= link_to '参加をキャンセルする', event_ticket_path(@event, @ticket), method: :delete, class: "btn btn-warning" %>
	<% elsif user_signed_in? %>
		<button class="btn btn-primary" data-toggle="modal" data-target="#createTicket">
			参加する
		</button>
		<div class="modal fade" id="createTicket" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title" id="dialogHeader">参加コメント</h4>
					</div>
					<%= form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f| %>
						<div class="modal-body">
							<%= f.text_field :comment, class: 'form-control' %>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
							<%= f.button '送信', class: "btn btn-primary", data: { disable_with: '送信中…' } %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

	<% else %>
	 <%= link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary" %>
	<% end %>
	<% end %>
</div>
</div>

app/views/smartphone/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "無料登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れてしまった方はこちら", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "本登録のメールが届かない方はこちら", new_confirmation_path(resource_name) %><br />
<% end -%>

app/views/smartphone/users/show.html.erb
<div class="row-fluid">
    <div class="span12">
      <h1>プロフィール</h1>
      <h2><%= @user.name %></h2>
      <div class="thumnail">
        <%= image_tag @user.user_image.url,:size => "100x100" %>
      </div>
      <h3><%= @user.name %></h3>
      <h3>投稿数:<%= @user.microposts.count %></h3>
      <h3>お役立ち数:<%= @user.microposts.count %></h3>
  </div>
</div>