config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :tickets
    resources :microposts do
      resources :favorites
    end
  end

  resources :questions do
    resources :answers
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  match 'users/:id' => 'users#show', via: :get
  resources :users, only: [:show]
  root "pages#index"
  get "pages/show"
  get "pages/help"
  get "pages/contact"
  get "pages/about"

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
	mount_uploader :event_image, EventImageUploader
	has_many :tickets, dependent: :destroy
	has_many :microposts, dependent: :destroy
	belongs_to :user, class_name: 'User'
	validates :name, length: { maximum: 50 }, presence: true
	validates :content, length: { maximum: 2000 }, presence: true

	def created_by?(user)
		return false unless user
		user_id == user.id
	end

	def self.ransackable_attributes(auth_object = nil)
		%w(name)
	end

	def self.ransackable_associations(auth_object = nil)
		[]
	end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :favorites
  mount_uploader :micropost_image, MicropostImageUploader

end

app/models/question.rb
class Question < ActiveRecord::Base
		belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
   	mount_uploader :user_image, UserImageUploader
    validates :name, presence: true, length: { maximum: 20}
    has_many :created_events, class_name: 'Event', foreign_key: :user_id
    has_many :tickets
    has_many :microposts
    has_many :favorites

    def self.from_omniauth(auth)
        where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.username = auth["info"]["nickname"]
        end
    end

    def self.new_with_session(params, session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"], without_protection: true) do |user|
                user.attributes = params
                user.valid?
            end
        else
            super
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	PER = 10
	before_filter :authenticate_user!

	def index
		if params[:category_id].nil?
			@search = Event.page(params[:page]).per(PER).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		else
			@search = Event.page(params[:page]).per(PER).where(category_id: params[:category_id]).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		end
	end

	def edit
		@event = current_user.created_events.find(params[:id])
	end

	def update
		@event = current_user.created_events.find(params[:id])
		if @event.update(event_params)
			redirect_to @event, notice: '更新しました'
		else
			render :edit
		end
	end

	def destroy
		@event = current_user.created_events.find(params[:id])
		@event.destroy!
		redirect_to root_path, notice: '削除しました'
	end

	def new
		@event = current_user.created_events.build
	end

	def create
		@event = current_user.created_events.build(event_params)
		if @event.save
			redirect_to @event, notice: 'いどばたを作成しました'
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
		@ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
		@tickets = @event.tickets.includes(:user).order(:created_at)
		@microposts = @event.microposts.includes(:user).order(:created_at)
	end

	private
	def event_params
		params[:event][:address_status] = current_user.address_status
		params.require(:event).permit(
			:name, :content, :category_id, :address_status,
			:event_image, :event_image_cache, :remove_event_image
		)
	end

	private
	def search_params
		params.require(:q).permit!
	rescue
		{ name_qteq: "" }
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	PER = 10
	before_filter :authenticate_user!

	def index
		@event = Event.find(params[:event_id])
		@microposts = @event.microposts.order(:created_at)
	end

	def create
		micropost = current_user.microposts.build do |m|
			m.event_id = params[:event_id]
			m.comment = params[:micropost][:comment]
			m.micropost_image = params[:micropost][:micropost_image]
		end
		if micropost.save
			redirect_to event_microposts_path(micropost.event), notice: '投稿が完了いたしました'
		else
			render json: { messages: micropost.errors.full_messages }, status: 422
		end
	end

	def destroy
		@micropost = Micropost.find(params[:id])
		@micropost.destroy!
		redirect_to event_microposts_path(@micropost.event), notice: '削除しました'
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    count = 0
    if user_signed_in?
      current_user.microposts.each do |m|
        count = count + m.favorites.count
      end
    end
    @count = count
  end

  def show
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :authenticate_user!

	def now
		raise ActionController::RoutingError 'ログイン状態で TicketsController#new にアクセス'
	end

	def create
		ticket = current_user.tickets.build do |t|
			t.event_id = params[:event_id]
			t.comment = params[:ticket][:comment]
		end
		if ticket.save
			flash[:notice] = 'このイベントに参加表明しました'
			head 201
		else
			render json: { messages: ticket.errors.full_messages }, status: 422
		end
	end

	def destroy
		ticket = current_user.tickets.find_by(event_id: params[:event_id])
		ticket.destroy!
		redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    	base_title = "Sil-地域子育て情報コミュニティ"
    	if page_title.empty?
      		base_title
    	else
      		"#{base_title} | #{page_title}"
    	end
  	end

  	def nl2br(str)
		str.gsub(/\r\n|\r|\n/, "<br />").html_safe
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pc/microposts/index.html.erb
<div>
	<h1>
		<%= @event.name %>のコメント一覧
	</h1>
</div>

	<ol class="microposts">
				<% @microposts.each do |micropost| %>
				<li>
						<% if micropost.user %>
						<span class="user">
						<%= link_to micropost.user.name, micropost.user %>
						</span>
						<span class="content">
							<%= auto_link(nl2br(micropost.comment), html: { target: '_blank' }, link: :urls) %>
						</span>
						<% if micropost.micropost_image? %>
						<div class="thumnail">
							<%= image_tag micropost.micropost_image.url %>
						</div>
						<% end %>
						<% else %>
						退会したユーザーです
						<% end %>
						<span class="timestamp">
 					     投稿日時: <%= micropost.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[micropost.created_at.wday]}) %H:%M:%S")  %>
   						</span>
   						<% if current_user == micropost.user %>
    <%= link_to "削除", event_micropost_path(id:micropost.id), method: :delete,
                                     data: { confirm: "本当に削除してもよろしいですか?" },
                                     title: micropost.comment %>
						  <% end %>
						  <% if current_user && current_user.favorites.find_by(micropost_id: micropost.id) %>
						    <%= link_to "お気に入り解除", event_micropost_favorite_path(@event, micropost, current_user.favorites.find_by(micropost_id: micropost.id)), method: :delete %>
						<% else %>
							<%= link_to "お気に入り",event_micropost_favorites_path(micropost_id: micropost.id), method: :post %>
						<% end %>
   				</li>
   			<% end %>
		</ol>

		<hr>

		<%= form_for(@event.microposts.build, url: event_microposts_path(@event)) do |f| %>
		<%= f.label :comment %>
		<%= f.text_field :comment, class: 'form-control' %>
		<div class="form-group">
			<%= f.file_field :micropost_image %>
			<%= f.hidden_field :micropost_image_cache %>
		</div>
		<%= f.button '投稿する', class: "btn btn-primary", data: { disable_with: '送信中…' } %>
		<% end %>	

app/views/smartphone/microposts/index.html.erb
<div>
	<h1>
		<%= @event.name %>のコメント一覧
	</h1>
</div>

	<ol class="microposts">
				<% @microposts.each do |micropost| %>
				<li>
						<% if micropost.user %>
						<span class="user">
						<%= link_to micropost.user.name, micropost.user %>
						</span>
						<span class="content">
							<%= auto_link(nl2br(micropost.comment), html: { target: '_blank' }, link: :urls) %>
						</span>
						<% if micropost.micropost_image? %>
						<div class="thumnail">
							<%= image_tag micropost.micropost_image.url %>
						</div>
						<% end %>
						<% else %>
						退会したユーザーです
						<% end %>
						<span class="timestamp">
 					     投稿日時: <%= micropost.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[micropost.created_at.wday]}) %H:%M:%S")  %>
   						</span>
   						<% if current_user == micropost.user %>
						    <%= link_to "削除", event_micropost_path(id:micropost.id), method: :delete,
                                     data: { confirm: "本当に削除してもよろしいですか?" },
                                     title: micropost.comment %>
                        <% end %>
                        <% if current_user && current_user.favorites.find_by(micropost_id: micropost.id) %>
						    <%= link_to "お気に入り解除", event_micropost_favorite_path(@event, micropost, current_user.favorites.find_by(micropost_id: micropost.id)), method: :delete %>
						<% else %>
							<%= link_to "お気に入り",event_micropost_favorites_path(micropost_id: micropost.id), method: :post %>
						<% end %>
   				</li>
   			<% end %>
		</ol>

		<hr>

		<%= form_for(@event.microposts.build, url: event_microposts_path(@event)) do |f| %>
		<%= f.label :comment %>
		<%= f.text_field :comment, class: 'form-control' %>
		<div class="form-group">
			<%= f.file_field :micropost_image %>
			<%= f.hidden_field :micropost_image_cache %>
		</div>
		<%= f.button '投稿する', class: "btn btn-primary", data: { disable_with: '送信中…' } %>
		<% end %>	