config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :tickets
    resources :microposts do
      resources :favorites
    end
  end

  resources :questions do
    resources :answers
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  match 'users/:id' => 'users#show', via: :get
  resources :users, only: [:show]
  root "pages#index"
  get "pages/show"
  get "pages/help"
  get "pages/contact"
  get "pages/about"

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
	mount_uploader :event_image, EventImageUploader
	has_many :tickets, dependent: :destroy
	has_many :microposts, dependent: :destroy
	belongs_to :user, class_name: 'User'
	validates :name, length: { maximum: 50 }, presence: true
	validates :content, length: { maximum: 2000 }, presence: true

	def created_by?(user)
		return false unless user
		user_id == user.id
	end

	def self.ransackable_attributes(auth_object = nil)
		%w(name)
	end

	def self.ransackable_associations(auth_object = nil)
		[]
	end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_many :favorites
  mount_uploader :micropost_image, MicropostImageUploader

end

app/models/question.rb
class Question < ActiveRecord::Base
		belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
   	mount_uploader :user_image, UserImageUploader
    validates :name, presence: true, length: { maximum: 20}
    has_many :created_events, class_name: 'Event', foreign_key: :user_id
    has_many :tickets
    has_many :microposts
    has_many :favorites

    def self.from_omniauth(auth)
        where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.username = auth["info"]["nickname"]
        end
    end

    def self.new_with_session(params, session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"], without_protection: true) do |user|
                user.attributes = params
                user.valid?
            end
        else
            super
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	PER = 10
	before_filter :authenticate_user!

	def index
		if params[:category_id].nil?
			@search = Event.page(params[:page]).per(PER).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		else
			@search = Event.page(params[:page]).per(PER).where(category_id: params[:category_id]).order(:created_at).search(search_params)
			@before_events = @search.result(distinct: true)
			@events = @before_events.where(address_status: current_user.address_status)
		end
	end

	def edit
		@event = current_user.created_events.find(params[:id])
	end

	def update
		@event = current_user.created_events.find(params[:id])
		if @event.update(event_params)
			redirect_to @event, notice: '更新しました'
		else
			render :edit
		end
	end

	def destroy
		@event = current_user.created_events.find(params[:id])
		@event.destroy!
		redirect_to root_path, notice: '削除しました'
	end

	def new
		@event = current_user.created_events.build
	end

	def create
		@event = current_user.created_events.build(event_params)
		if @event.save
			redirect_to @event, notice: 'いどばたを作成しました'
		else
			render 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
		@ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
		@tickets = @event.tickets.includes(:user).order(:created_at)
		@microposts = @event.microposts.includes(:user).order(:created_at)
	end

	private
	def event_params
		params[:event][:address_status] = current_user.address_status
		params.require(:event).permit(
			:name, :content, :category_id, :address_status,
			:event_image, :event_image_cache, :remove_event_image
		)
	end

	private
	def search_params
		params.require(:q).permit!
	rescue
		{ name_qteq: "" }
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    count = 0
    if user_signed_in?
      current_user.microposts.each do |m|
        count = count + m.favorites.count
      end
    end
    @count = count
  end

  def show
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    	base_title = "Sil-地域子育て情報コミュニティ"
    	if page_title.empty?
      		base_title
    	else
      		"#{base_title} | #{page_title}"
    	end
  	end

  	def nl2br(str)
		str.gsub(/\r\n|\r|\n/, "<br />").html_safe
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pc/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.4";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/pc/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Sil-地域子育て情報コミュニティ
  </small>
  <nav>
    <ul>
      <li><div class="fb-page" data-href="https://www.facebook.com/pages/Sil-%E5%9C%B0%E5%9F%9F%E5%AD%90%E8%82%B2%E3%81%A6%E6%83%85%E5%A0%B1%E5%85%B1%E6%9C%89%E3%82%B5%E3%82%A4%E3%83%88/147804055556383?fref=ts" data-width="300" data-height="200" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pages/Sil-%E5%9C%B0%E5%9F%9F%E5%AD%90%E8%82%B2%E3%81%A6%E6%83%85%E5%A0%B1%E5%85%B1%E6%9C%89%E3%82%B5%E3%82%A4%E3%83%88/147804055556383?fref=ts"><a href="https://www.facebook.com/pages/Sil-%E5%9C%B0%E5%9F%9F%E5%AD%90%E8%82%B2%E3%81%A6%E6%83%85%E5%A0%B1%E5%85%B1%E6%9C%89%E3%82%B5%E3%82%A4%E3%83%88/147804055556383?fref=ts">Sil - 地域子育て情報共有サイト</a></blockquote></div></div></li>
      <li><%= link_to "運営団体",   pages_about_path %></li>
      <li><%= link_to "ヘルプ", pages_help_path %></li>
      <li><%= link_to "お問い合わせ", pages_contact_path %></li>
      <li></li>
    </ul>
  </nav>
</footer>

app/views/pc/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to image_tag("logo.jpg"), root_path, id: "logo"  %>
          <h2><i>Sil-地域子育て情報コミュニティ</i></h2>
          <% if user_signed_in? %>
          <ul id="loginNav">
            <%= search_form_for(@search, url: events_path) do |f| %>
              <li>
              <%= button_tag( class: "btn btn-default btn-sm") do %>
                <%= content_tag :span, "検索", class: "glyphicon glyphicon-search" %>
              </li>
              <li>
              <%= f.text_field :name_cont, :placeholder => "いどばた検索", :size => "20px" %>
              </li>
              <% end %>
            </ul>
            <% end %>

          <% else %>
          <ul id="unloginNav">
            <li>
                <%= link_to 'ログイン', new_user_session_path %>
            </li>
            <li>
            <%= link_to '無料登録', new_user_registration_path %>
            </li>
            <li><%= link_to "ヘルプ", pages_help_path %></li>
          </ul>
          <% end %>
        </ul>
    </div>
</header>

app/views/pc/layouts/_sidebar_left.html.erb
<div class="navbar-inner">
    <div>
      <nav>
        <ul class="nav">
          <li><%= link_to 'サイト利用者交流', events_path(category_id: 7), class: "myButton myButton7" %></li>
          <li><%= link_to '地域イベント・遊び場', events_path(category_id: 1), class: "myButton myButton1" %></li>
          <li><%= link_to '病院関連', events_path(category_id: 2), class: "myButton myButton2" %></li>
          <li><%= link_to '教育機関', events_path(category_id: 4), class: "myButton myButton4" %></li>
          <li><%= link_to 'おさがりフリマ', events_path(category_id: 5), class: "myButton myButton5" %></li>
        </ul>
      </nav>
    </div>
  </div>

app/views/pc/layouts/_sidebar_right.html.erb
<div class="navbar-inner sidebar-right">
    <div>
      <nav>
        <ul class="nav">
          <li><%= link_to "ホーム", root_path, class: "glyphicon glyphicon-home rightBtn" %></li>
          <li><%= link_to 'プロフィール変更', edit_user_registration_path, class: "glyphicon glyphicon-file rightBtn" %></li>
          <li><%= link_to 'いどばた一覧', events_path, class: "glyphicon glyphicon-edit rightBtn" %></li>
          <li><%= link_to 'いどばた立ち上げ', new_event_path, class: "glyphicon glyphicon-edit rightBtn" %></li>
          <li>
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out rightBtn" %>
                </li>
        </ul>
      </nav>
    </div>
  </div>

app/views/pc/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title><%= full_title(yield(:title)) %></title>
</head>
<body>
	<%= render 'layouts/facebook' %>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
	<div class="row">
		<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<% if user_signed_in? %>
		<div class="col-xs-2">
		<%= render 'layouts/sidebar_left' %>
		</div>
		<div class="col-xs-8">
		<%= yield %>
		</div>
		<div class="col-xs-2">
		<%= render 'layouts/sidebar_right' %>
		</div>
		<% else %>
		<div class="col-xs-12">
		<%= yield %>
		</div>
		<% end %>
	</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/smartphone/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.4";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/smartphone/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to image_tag("logo.jpg"), root_path, id: "logo"  %>
          <% if user_signed_in? %>
            <nav>
              <button href="#" class="btn btn-primary navBtn btn-sm pull-right dropdown-toggle menu-btn" data-toggle="dropdown">MENU
              </button>
              <ul class="pull-right dropdown-menu">
                <li><%= link_to "ホーム", root_path, class: "glyphicon glyphicon-home" %></li>
                <% if signed_in? %>
                <li><%= link_to 'プロフィール変更', edit_user_registration_path, class: "glyphicon glyphicon-file" %></li>
                <li><%= link_to 'いどばた', new_event_path, class: "glyphicon glyphicon-edit" %></li>
                <li>
                <li class="divider"></li>
                <li><%= link_to 'サイト利用者交流', events_path(category_id: 7) %></li>
                <li><%= link_to '地域イベント・遊び場', events_path(category_id: 1) %></li>
                <li><%= link_to '病院関連', events_path(category_id: 2) %></li>
                <li><%= link_to '子育て相談', events_path(category_id: 4) %></li>
                <li><%= link_to 'おさがりフリマ', events_path(category_id: 5) %></li>
                <li class="divider"></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
                </li>
               <% else %>
            <li><%= link_to "ログイン", signin_path %></li>
          <% end %>
        </ul>
      </nav>
      <ul id="loginNav">
            <%= search_form_for(@search, url: events_path) do |f| %>
              <li>
              <%= button_tag( class: "btn btn-default btn-sm") do %>
                <%= content_tag :span, "検索", class: "glyphicon glyphicon-search" %>
              </li>
              <li>
              <%= f.text_field :name_cont, :placeholder => "検索", :size => "9%" %>
              </li>
              <% end %>
            </ul>
            <% end %>

          <% else %>
          <ul id="unloginNav">
            <li>
                <%= link_to 'ログイン', new_user_session_path %>
            </li>
            <li>
            <%= link_to '無料登録', new_user_registration_path %>
            </li>
            <li><%= link_to "ヘルプ", pages_help_path %></li>
          </ul>
          <% end %>
        </ul>
    </div>
</header>

app/views/smartphone/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67244776-1', 'auto');
  ga('send', 'pageview');

	</script>
  <title><%= full_title(yield(:title)) %></title>
</head>
<body>
	<%= render 'layouts/facebook' %>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
	<div class="row">
		<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<div class="col-sm-12">
		<%= yield %>
		</div>
	</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/smartphone/pages/about.html.erb
<% provide(:title, '運営団体') %>
<h1>運営団体</h1>
<p>
  <table class="company">
  <tr>
    <th class="arrow_box">運営媒体名</td>
    <td>Sil</td>
  </tr>
  <tr>
    <th class="arrow_box">運営責任者</td>
    <td>駒崎琴美</td>
  </tr>
  <tr>
    <th class="arrow_box">コンセプト</td>
    <td>顔の知らない地域のママと、子育て情報を共有する</td>
  </tr>
  </table>
</p>

app/views/smartphone/pages/contact.html.erb
<h1>お問い合わせフォーム</h1>
<p>工事中………</p>

app/views/smartphone/pages/help.html.erb
<% provide(:title, 'ヘルプ') %>
<h1>ヘルプ</h1>
<p>工事中……</p>

app/views/smartphone/pages/index.html.erb
<% if user_signed_in? %>
  <div class="row-fluid">
    <div class="span12">
      <h1>プロフィール</h1>
      <h2><%= current_user.name %></h2>
      <div class="thumnail">
        <%= image_tag current_user.user_image.url,:size => "100x100" %>
      </div>
      <h3>投稿数:<%= current_user.microposts.count %></h3>
      <h3>お役立ち数:<%= @count %></h3>
    </div>
  </div>
<% else %>

	<div class="keyVisualContainer-smartphone">
    	<div class="keyVisualContent">
        <h1>「井戸端会議」のような感覚で地域情報を<br>共有してみませんか？</h1>
      	<h2>
      		地域子育て情報コミュニティ「Sil」で<br />新しい体験を
      	</h2>
      </div>
  </div>
  <div class="center">
      <%= link_to "「Sil」に登録するにはこちらから！", new_user_registration_path,
                                class: "btn btn-large btn-danger" %>
	</div>
<% end %>

app/views/smartphone/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>